default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flex-dev

test:
  <<: *default
  database: flex-test

production:
  <<: *default
  database: flex-production
